apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp 
spec:
  replicas: 6
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp 
    spec:
      containers:
        - name: sampleapp
          image: demoossacr.azurecr.io/sampleapp:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
